#!/usr/bin/bash

selected=$({ 
  echo "$HOME/.dotfiles";
  fd . ~/Github/ --type directory --exact-depth 2; 
  fd . ~/Learn/ --type directory --exact-depth 1; 
} | fzf)


if [[ -z $selected ]]; then
  exit 0
fi


project_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

echo $TMUX;
echo $tmux_running;

ps aux | grep $tmux_running;

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  echo "something"
fi

# When tmux is not running
if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  echo "HERE"
  tmux -u new-session -s $project_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$project_name 2> /dev/null; then
  tmux -u new-session -ds $project_name -c $selected
fi

echo "HELLO"

tmux -u switch-client -t $project_name

