format = """$username\ 
$hostname\ 
$localip\ 
$directory\ 
$git_branch\ 
$git_commit\ 
$git_state\ 
$git_metrics\ 
$git_status
$character
"""

[cmd_duration]
disabled = true

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold green)'

