#!/usr/bin/env bash

SELECTED=$(find ~/Github/ ~/Learn/ ~/Studious/ -mindepth 1 -maxdepth 1 | fzf);
PROJECT_NAME=$(basename $SELECTED);

tmux start-server;

if ! $(tmux has-session -t $PROJECT_NAME); then
  if [ -f "$SELECTED/.tmux-script" ]; then
      tmux -u new-session -c $SELECTED -s $PROJECT_NAME -d "bash .tmux-script"
  else
      tmux -u new-session -c $SELECTED -s $PROJECT_NAME -d
  fi
fi

if ! $(tmux -u attach-session -t $PROJECT_NAME:1); then
    tmux -u switch-client -t $PROJECT_NAME:1
fi

